"""增加管理后台部分

Revision ID: 2bf08b2224bf
Revises: 5f66e2341df8
Create Date: 2021-12-15 19:47:57.071907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf08b2224bf'
down_revision = '5f66e2341df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locked', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.drop_column('user', 'locked')
    # ### end Alembic commands ###
