"""User模型增加avatar_raw字段

Revision ID: 4f8b4aeb9460
Revises: ad8e720463d1
Create Date: 2021-12-07 16:16:02.114113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8b4aeb9460'
down_revision = 'ad8e720463d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_raw', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_raw')
    # ### end Alembic commands ###
