"""为User模型增加public_following public_follower字段

Revision ID: 5f66e2341df8
Revises: d600d9442cc6
Create Date: 2021-12-07 18:15:21.981237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f66e2341df8'
down_revision = 'd600d9442cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_followers', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('public_following', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_following')
    op.drop_column('user', 'public_followers')
    # ### end Alembic commands ###
