"""用户设置相关

Revision ID: ad8e720463d1
Revises: 6507a07254c2
Create Date: 2021-12-07 16:08:18.828107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8e720463d1'
down_revision = '6507a07254c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('receive_comment_notification', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('receive_follow_notification', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('receive_collect_notification', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('show_collections', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_collections')
    op.drop_column('user', 'receive_collect_notification')
    op.drop_column('user', 'receive_follow_notification')
    op.drop_column('user', 'receive_comment_notification')
    # ### end Alembic commands ###
